import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=relative=>fs.readFileSync(path.join(root,relative),'utf8');
const json=relative=>JSON.parse(read(relative));
const safe=value=>JSON.stringify(value).replaceAll('<','\\u003c').replaceAll('>','\\u003e').replaceAll('&','\\u0026');
const tokens=json('ui/tokens.json'), manifest=json('ui/data/manifest.json');
const files=Object.fromEntries(Object.entries(manifest.files).map(([name,hash])=>{const bytes=fs.readFileSync(path.join(root,'ui/data',name));if(createHash('sha256').update(bytes).digest('hex')!==hash)throw Error('Input hash mismatch '+name);return[name,JSON.parse(bytes)];}));
const icons=Object.fromEntries(fs.readdirSync(path.join(root,'ui/vendor/icons')).filter(name=>name.endsWith('.svg')).map(name=>[name.slice(0,-4),read('ui/vendor/icons/'+name).replace(/<!--[^]*?-->/g,'').replace('<svg ','<svg aria-hidden="true" focusable="false" ')]));
const font=fs.readFileSync(path.join(root,'ui/vendor/AtkinsonHyperlegible-Regular.ttf')).toString('base64');
const serif=fs.readFileSync(path.join(root,'ui/vendor/IBMPlexSerif-Regular.ttf')).toString('base64');
let reference=read('reference-js/reference.mjs').replace(/^import .*;\r?\n/gm,'').replace(/const schema = [^\n]+/,`const schema = ${JSON.stringify(json('schema/blastradius-graph-v0.1.schema.json'))};`).replace(/const digest = [^\n]+/,'const digest = value => sha256(value);').replaceAll('export function ','function ');
reference=reference.slice(0,reference.indexOf('if (process.argv[1]'));
reference+='\nglobalThis.BRReference={fromText,canonical,parse,inspect(graph,id,model){const validated=validate(parse(JSON.stringify(graph)));return calculateReach(validated.nodes,validated.edges,validated.nodes.get(id),model);}};';
reference='(function(){'+reference+'})();';
const css=`@font-face{font-family:'Atkinson Hyperlegible';src:url(data:font/ttf;base64,${font}) format('truetype');font-display:swap}@font-face{font-family:'IBM Plex Serif';src:url(data:font/ttf;base64,${serif}) format('truetype');font-display:swap}:root{${Object.entries(tokens.color).filter(([,value])=>typeof value==='string').map(([key,value])=>`--${key}:${value}`).join(';')}}`+read('ui/styles.css');
const assets=['d3.min.js','sha256.min.js','jspdf.umd.min.js','svg2pdf.umd.min.js','axe.min.js'];
const parts={__CSS__:css,__VENDOR__:assets.map(name=>read('ui/vendor/'+name)).join('\n'),__REFERENCE__:reference,__DATA__:`globalThis.BR_INPUT=${safe({manifest,files,tokens,icons,font,serif})};`,__RENDER__:read('ui/render.js')+'\n'+read('ui/population.js'),__APP__:read('ui/app.js')};
const html=read('ui/index.template.html').replace(/__CSS__|__VENDOR__|__REFERENCE__|__DATA__|__RENDER__|__APP__/g,match=>parts[match]);
fs.writeFileSync(path.join(root,'ui/index.html'),html);
fs.writeFileSync(path.join(root,'ui/reference.browser.js'),reference);
console.log(JSON.stringify({html_bytes:Buffer.byteLength(html),result_files:Object.keys(files).length,sha256:createHash('sha256').update(html).digest('hex')}));