import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const rows=`1|Static architecture|One self-contained file opens without a server; no telemetry or network dependency. The build records vendored asset hashes and leaves engine result v0.1 unchanged.
2|Shared tokens|UI, SVG and paper exports consume the same JSON tokens. Color-vision simulations and contrast measurements are saved and any failed pair is repaired before a pass claim.
3|Open icon vocabulary|Principal, credential and constraint kinds resolve to attributed CC-BY SVG icons. Accessible names remain available without relying on the icon or color.
4|Normative visual annex|Publish Visual Vocabulary v0.1 with area, step, certainty, fixed-sensitivity and stamp rules. Every supported renderer is checked against the accompanying checklist.
5|Component gallery|A gallery renders each implemented view against an exercising result fixture. Empty, blocked, undefined and long-label states are included rather than only a flattering default.
6|Semantic zoom|Navigate only hierarchy explicitly present in input metadata. Acceptance requires stable breadcrumbs and reversible parent/child transitions; the current schema does not supply subscription/group hierarchy, so it is not fabricated.
7|Search grammar|Document type, radius comparison and name predicates with explicit error behavior. The same parsed predicate filters all relevant population visuals and their text tables without changing the full resource denominator.
8|Shareable view state|A URL fragment identifies the snapshot hash, view, model and ordinal selection. No tenant or credential names/IDs enter the fragment; reopening a known embedded snapshot restores the state.
9|Deterministic pseudonyms|One control replaces all displayed names and relevant export labels with stable local pseudonyms. Acceptance includes titles, tables, tooltips, evidence, annotations and a visible redaction stamp; pseudonymization is not anonymity.
10|Light dark print|Light and dark UI tokens preserve contrast; figures remain a declared paper style. An A3 print portrait removes controls without omitting provenance or implying an independent report.
11|Blast disc|Disc area follows canonical radius on a fixed reference footprint; marks encode resource-action pairs by first escalation step and sensitivity. Zero reach has zero filled area and every mark has an evidence alternative.
12|Step propagation|Play, pause, backward/forward step and scrub expose the same step ordering. Reduced motion presents final state without losing manual step access; elapsed animation time never claims attack duration.
13|Tenant treemap|Rectangle area is absolute reach and color is principal type. A p95 outline has an explicit population/tie rule, zero-area credentials remain in the table, and selection opens the corresponding disc.
14|Reach sunburst|Partition one credential's unique pairs by resource type, sensitivity bin and action without duplicating paths. Acceptance requires conserved counts at each hierarchy level and a readable linear table fallback.
15|Plane cross-section|Separate principal, binding and resource strata using explicit node kinds. No implied cloud boundary or network distance is added; crossing links retain direction, provenance and escalation labels.
16|Gravity layout|Do not ship orbital distance as a second unexplained risk score. A proposed alternative is fixed-axis small multiples; acceptance requires a declared distance function and evidence that overlap does not hide small credentials.
17|Egocentric graph|Show selected-credential reachable states with deterministic layout and an explicit node budget. Bundling must expose the underlying multiplicity and cannot erase distinct actor contexts or deny semantics.
18|Same-scale small multiples|Render compatible tenant or declared-group results with a common full-universe reference area. Acceptance rejects incomparable resource granularities and labels every numerator and denominator.
19|Granted versus used|Usage is absent from the current result contract, so no inner usage ring is invented. A future version must define observation window, missingness and action-level matching before two rings can be compared.
20|Model outlines|Overlay only independently computed default, strict and session-aware discs with named outlines and a common reference area. Atomic model changes avoid implying that interpolated states are valid authorization models.
21|Subway witness|Stations and directed edges represent the engine's chosen explanatory witness. Escalation interchanges, barriers, unknown/assumed segments and step versus hop counts must remain distinguishable.
22|Station provenance|Keyboard and pointer activation expose connector, source API, observed_at and evidence reference. Acceptance checks every node/edge station and restores focus when its evidence dialog closes.
23|Alternative paths|Show at most three independently enumerated valid alternatives with their actor contexts and divergence points. The current result includes one canonical witness; alternatives need verified enumeration rather than duplicated decorative routes.
24|Path intervention|A binding station can open the existing binding-removal counterfactual. Arbitrary edge deletion is not mislabeled a supported binding intervention; unsupported edge kinds explain the limitation.
25|Deterministic narrative|Build a factual sequence from witness edge kinds and provenance, with no language model. Copy exports plain text and retains the model, evidence and synthetic qualification rather than making a ticketing integration.
26|Research summaries|Replace the executive-sales framing with a data-derived research abstract for selected credentials. Acceptance requires exact reach, assumptions and limitations in exported Markdown, with no predicted-loss prose.
27|Secret unfolding|Reveal only explicitly modeled stored-credential links after the required read_secret capability is present. Metadata access must not unfold invented credentials or imply that all vault contents were read.
28|Trust bridges|Use platform regions only when an input extension provides authoritative boundary labels. Every bridge must map to an explicit assumption/federation capability; provider names in provenance are not sufficient.
29|Guest crossings|A versioned boundary/guest classification is needed before counting crossings. Acceptance excludes guessed guest status from names or domains and shows unknown classification separately.
30|Witness by model|Display the independently selected path or an explicit absence for each required model. Do not simply remove stations from a different model's witness and call the remnant a valid route.
31|Model control|Switch all credential results to the selected computed model and list every delta against a fixed baseline. Discrete redraw replaces misleading intermediate-model numeric tweening; reduced motion preserves all comparisons.
32|Binding surgery|Remove or add one validated binding and recompute per-credential and tenant metrics on a fixed universe. Restoring the source snapshot is reversible; invalid actions and graph shapes reject without retaining a misleading score.
33|Evaluated changes|Show five supplied single-binding evaluations and their before/after p95 discs. State candidate count and zero-improvement outcomes; never label the set globally optimal or multi-change minimal.
34|Path choke points|Count use by the selected canonical high-radius witnesses, not all possible paths. Acceptance labels that limited denominator and recomputes a proposed removal before claiming an actual effect.
35|Weight policy editor|Edit declared sensitivity weights with bounds and a visible policy-choice notice. The changed weights and result hash must be exported; no silently updated canonical radius or empirical-risk interpretation is permitted.
36|Variant disagreement|Compare ordinal rankings for canonical, sensitivity and action variants using deterministic tie rules. A flag explains the chosen threshold and is not a claim that a tool or tenant is gaming deliberately.
37|Local annotations|Notes remain in opt-in browser storage and export as a versioned JSON sidecar. They never modify engine evidence or silently enter public exports; redaction and deletion are testable.
38|Snapshot comparison|Accept two compatible results and show added/removed capabilities with fixed population and universe qualifications. Unknown inventory coverage must prevent a false improvement claim from missing resources.
39|Target planning|The engine evaluates single changes, not a global optimizer, so no minimal ordered plan is fabricated. A future planner needs a declared search objective, cost model and optimality bound; current evaluated choices remain separate.
40|Command palette|A keyboard command dialog exposes all supported view and export actions with focus return. Commands must mirror visible controls and never execute network or platform mutations.
41|Lorenz and Gini|Compute a sorted cumulative curve from per-credential reach and annotate the exact top share. The sum may overlap across credentials and must not be described as unique tenant surface.
42|Typed histogram|Use fixed canonical bins and grouped principal-type counts with a threshold marker. Linear and explicitly labeled log(1+count) scales preserve zero counts without deceptive log stacking.
43|Benchmark position|No real anonymized comparison population exists in this artifact. A future percentile requires a compatible released cohort and uncertainty; synthetic distributions cannot be presented as enterprise percentiles.
44|Public benchmark shell|A static methodology/download view may render the approved aggregate file. It must visibly state synthetic or pending status, release budget and cohort limits, with no pretend contributor count.
45|State report figures|Generate report charts only from a released aggregate and preserve suppression/noise metadata. The existing report template remains a template until governance and real-data gates are satisfied.
46|Reach flow|Naive Sankey flows can double-count shared bindings and violate conservation. Redesign around an explicitly unique attribution scheme or pair-overlap matrix; acceptance proves conservation and explains overlap losses.
47|Boundary chord|A chord requires declared boundary metadata and a precise directed pair-count definition. It cannot infer subscriptions/accounts from resource names or convert duplicate trust paths into additional exposure.
48|Team budgets|Teams, budgets and time snapshots are not supplied by the current contract. Specify an optional policy sidecar and comparable history; no invented team scorecard or compliance status is shown.
49|Resource shadow map|Invert computed reach to count how many credentials reach each resource-action pair. Rank exposure with sensitivity and principal-type mix, keeping credential counts distinct from unique resources.
50|Synthetic population explorer|Parameter controls invoke a documented local synthetic generator with a fixed seed. Every resulting distribution says illustrative and never uses animation as a substitute for engine completion.
51|Non-human lens|Filter service, managed, workload and AI-agent identities while comparing human/NHI count, median and p95. The denominator and whether statistics concern credentials or principals are explicitly labeled.
52|Agent budget|A gauge needs an explicit policy ceiling with a version and scope. No default threshold is falsely described as a real agent task budget; missing ceilings show unavailable.
53|Identity lineage|Creation lineage is not inferred from an authorization edge. A future creator relation requires provenance and time, with unknown creators preserved rather than a fabricated branching story.
54|Lifetime strip|Validity and last-used windows require corresponding fields and observation coverage. Missing telemetry must not become never-used, stale or expired; absent data renders an unavailable state.
55|Radius time-lapse|Animate only a sequence of comparable, independently computed snapshots. Assignment attribution must be proven by a counterfactual, not assumed from a simultaneous timestamp.
56|Threshold regressions|Compare exact before/after radii for shared credentials and label inventory/model changes. New identities and missing observations form separate classes, not automatic regressions.
57|Ephemeral timeline|Task appearance and expiry require explicit validity evidence. A view must distinguish deletion, observation gaps and real expiration; no synthetic clock progression masquerades as recorded history.
58|Federation lens|Use explicit trust edges with declared source/target identity boundaries. The lens must retain credential scope and unknown OIDC conditions rather than treating every federation label as unconditional access.
59|Task containment|Require a supplied task-scope set and compute set difference against reachable pairs. A missing task scope cannot yield zero out-of-scope access or a containment success badge.
60|Human machine violin|Use a declared bandwidth and enough observations for a meaningful density. For small fixture populations use an exact dot plot instead of a smooth distribution that implies unsupported precision.
61|Certainty overlay|Dash explicit assumed edges and compute dependent reach by removing those allow transitions. Unknown metadata remains unknown; illustrative annotations, alternative exact routes and the ratio denominator are disclosed.
62|Reproducibility stamp|Every view and SVG/PNG/PDF includes snapshot hash, engine/schema, model, parameters, snapshot time and vocabulary version. Redaction and illustrative status persist through exports.
63|Observation timeline|Plot supplied observation times only, not inferred event occurrence. Staleness thresholds are declared policy choices and simultaneous fixture timestamps are not presented as a real history.
64|Connector freshness|Compute age relative to an explicitly selected reference time, not ambient time in deterministic exports. Unknown or mixed source coverage must not receive a healthy freshness badge.
65|Structural silhouette|Render the exact local dry-run payload and make raw JSON accessible. Rename the anonymized claim: exact structural summaries are not anonymous and the current instrument submits nothing.
66|Local versus shared|Compare the closed dry-run field allowlist with fields retained locally. No upload button or submission promise is added; the exact difference is inspectable in JSON and text.
67|Linkage warning|Show measured synthetic uniqueness with its population and limitations before any hypothetical submission context. It is not a real-company re-identification probability or a safety certificate.
68|Network ledger|Instrument or audit attempted runtime requests and report local file/embedded asset behavior. Acceptance includes a no-network test, not merely a decorative offline badge.
69|Data and computation|Every shipped chart exposes its tabular values and the specification clause/code path used. Truncation, pagination and filter scope are explicit; unsupported computations cannot borrow an unrelated definition.
70|Assumption ledger|Show declared sensitivity choices, visual approximation annotations and public-reconstruction assumptions. Ledger entries are evidence context, not engine permissions or externally validated facts.
71|Fixture playground|Edit a tiny graph, add resource/grant/constraint and recompute through the reference engine. Invalid presets and mutations suppress scores and show rejection; derivations remain attached to their original fixture, not falsely to edited graphs.
72|Reconstruction gallery|Each sourced minimal graph selects its credential and exposes control and assumption ledger. Historical rank remains unidentifiable; a toy first rank cannot become a real top-decile claim.
73|Guided tour|A short optional sequence walks through actual evidence states without blocking ordinary navigation. Each overlay is keyboard-dismissable and restores focus; no scripted number differs from the engine result.
74|Reading overlay|Provide optional encoding definitions and a text equivalent per view. It must not cover critical controls or turn the instrument into a marketing landing page.
75|Specification browser|Map numbered requirements to frozen fixtures and code paths. Manual requirements are identified as manual; a click must open the actual relevant fixture rather than a generic success page.
76|Conformance viewer|Show requirement-by-tool outcomes and explicit manual/uncovered cells. Any downloadable self-claim includes suite/tool version and never implies certification or external endorsement.
77|Glossary|Terms such as radius, absolute reach, p95 and escalation expose concise definitions on keyboard focus/activation. A tooltip cannot be the only way to obtain a critical definition.
78|Talk mode|Use deterministic pseudonyms, a declared larger layout and reversible prepared state sequence. No names remain in the DOM, figure metadata or evidence drawer when redaction is claimed complete.
79|Embedded static demo|Publish an embeddable fixture-driven visual with the same engine result and vocabulary stamp. It must remain useful offline and retain a text alternative in constrained hosts.
80|Classroom exercises|Questions compare learner predictions with exact fixture outcomes and explain counterexamples. Correctness is computed, not a hardcoded visual celebration; no personal learner telemetry is retained.
81|Byte-identical SVG|Same input, tokens, font bytes and options produce byte-identical SVG across repeated rendering. The test covers all renderers and input permutations allowed by the contract.
82|IEEE export|Export SVG, PNG and PDF at declared single/double-column widths with embedded open fonts and full stamps. Tests inspect dimensions, nonblank pixels and PDF font embedding; tiny illegible scaled labels are not a publication-quality pass.
83|Paper figure command|Provide make figures and a direct no-make equivalent that generate the complete declared figure set from result JSONs. Captions identify the input hashes, encodings, widths and synthetic limitations.
84|Embeddable component|A blast-radius custom element consumes a result and options with no network requirement. It retains keyboard/evidence alternatives and rejects unsupported result formats instead of silently rendering arbitrary data.
85|Terminal view|A tty formatter may show sparkline bins, ranked counts and ASCII witness with the same definitions. It must preserve undefined values and work without terminal color; no extra live collector is introduced.
86|Notebook wrapper|A notebook widget wraps the static component or embeds self-contained HTML safely. It needs a tested notebook frontend contract and cannot claim widget support from an unexecuted screenshot.
87|Declarative charts|Publish a versioned declarative chart description for statistical views, including data fields, transforms and scale domains. Community extensions must reproduce exact tables and stamps.
88|View plugins|A static manifest declares inputs, encodings, dependencies, licence and review status. Loading arbitrary untrusted script plugins is out of scope; review must cover truthfulness, privacy and accessibility.
89|Markdown deltas|Export per-credential before/after Markdown from compatible results, with evidence and fixed-universe qualifications. This is a local artifact, not a ticketing or CI service integration.
90|Headless screenshots|A local command opens a view, waits for fonts/engine readiness and saves a reproducible viewport capture. Screenshot state and viewport metadata are recorded; hidden-tab animation artifacts are not mistaken for UI failures.
91|Accessibility gate|Run WCAG2.2 AA-tagged automated checks with zero critical issues on all shipped views and keyboard workflows. Report full results and manual gaps; zero automated violations alone is not full WCAG certification.
92|Text alternatives|Every chart has a narrated description and inspectable data table; paths have deterministic prose. Optional speech is opt-in and never required to access evidence.
93|Reduced motion|The operating-system preference disables propagation animation and all optional transitions without omitting a reachable step. Manual step/scrub and before/after evidence remain available.
94|Large-population budget|Use canvas for10000 credentials and explicit aggregation for50000, based on fresh engine results. Report observed frame/render timings, hardware/runtime and scope; do not assert60fps from a static screenshot.
95|Visual regression|Save and compare screenshots for every shipped view on explicit fixtures at desktop/mobile dimensions. Tests report count and pixel differences with deterministic state/fonts; baselines are review artifacts, not unexplained golden files.
96|Browser matrix|Record actual Chromium, Firefox and Safari execution status separately. An unavailable engine is not marked pass; compatibility limitations and a viable external test plan remain visible.
97|Internationalization|Externalize English strings and use locale-aware formatting under a declared locale option. Deterministic figure exports fix the locale and do not silently depend on the host machine.
98|UI threat model|No telemetry, eval or runtime CDN; strict CSP blocks connections and unsafe content insertion. Document the inline static-bundle exception, dependency versions, hash inventory and private-signature verification limitations.
99|Design-system guide|Document tokens, accessible component states, encoding rules and contribution checks. New visuals need an exercising fixture, common-scale proof, text alternative and deterministic export test.
100|Complete goal register|Maintain all100 stable goal IDs with shipped/stubbed/specified/backlog status, acceptance paragraph and owner slot. Include ten new theme proposals, explicit rejected redesigns and a visual-conformance checklist.`.trim().split('\n').map(line=>{const[id,title,acceptance]=line.split('|');return{id:Number(id),title,acceptance};});
const tier1=new Set([1,2,3,4,11,12,13,21,22,31,32,33,41,42,51,61,62,65,71,72,81,82,83,91,92,94,95,100]);
const shipped=new Set([1,2,3,4]);
const stubbed=new Set([7,8,10,11,12,13,21,22,24,25,31,32,33,41,42,51,61,62,65,66,67,69,70,71,72,75,76,77,81,82,91,92,93,98]);
const proposals=[
 ['A','Denominator ruler','Show the full-universe footprint beside every disc so dilution is physically visible. Acceptance: unchanged absolute reach with a larger universe shrinks only the ratio disc, and both denominators remain visible.','built in the disc reference outline'],
 ['B','Step-mass strip','A compact strip records newly reached pair counts at each escalation cost. It makes a large one-step jump visible without suggesting elapsed attack time; acceptance compares each bin with minimum path costs.','proposed'],
 ['C','Witness receipt','Hash the ordered witness edge IDs and display a compact receipt next to the path. It exposes path changes even when the final score is unchanged; acceptance checks stable receipts and changed-route counterexamples.','proposed'],
 ['D','Zero-effect intervention ledger','Show evaluated changes that do not affect p95 alongside changes that do. This prevents the top-five display from hiding redundant paths; acceptance uses actual exhaustive single-binding results and avoids a global optimum claim.','proposed'],
 ['E','Overlap dual ledger','Place summed credential-pair exposure beside the unique pair union. The gap physically demonstrates why a Lorenz annotation is not total exposed surface; acceptance derives both from exact reach sets.','proposed'],
 ['F','Count-versus-reach dumbbell','Compare NHI population share with its share of summed exposure, with human overlap separately labeled. Acceptance avoids interpreting an extensive union as disproportionate individual privilege.','proposed'],
 ['G','Unknown-evidence floor','Reserve a visible unknown band when certainty metadata is absent rather than drawing an empty uncertainty overlay. Acceptance tests a result with no ledger and prohibits an automatic0% confidence burden.','built as explicit unknown state'],
 ['H','Rank countermodel switch','Toggle two source-consistent population completions that move the same compromised credential from first to tenth. Acceptance labels both invented backgrounds and keeps actual historical rank unidentified.','proposed'],
 ['I','Reproduction receipt','A one-click local proof compares two SVG byte streams and exposes their digest and options. Acceptance detects a changed token or option and never uses a visual similarity score as byte identity.','proposed'],
 ['J','Truthfulness lint','Automated checks inspect marks for declared denominators, fixed scales, stamps and unknown states before visual review. Acceptance fails deliberately malformed SVG metadata and pairs a machine report with manual review gaps.','proposed']
];
const overrideFile=path.join(root,'ui/goal-status.json');
const overrides=fs.existsSync(overrideFile)?JSON.parse(fs.readFileSync(overrideFile,'utf8')):{};
const goals=rows.map(row=>({...row,tier:tier1.has(row.id)?'T1':'T2',status:overrides[row.id]??(shipped.has(row.id)?'shipped':stubbed.has(row.id)?'stubbed':'specified'),owner:'Unassigned; maintainer/reviewer slot'}));
const counts=goals.reduce((summary,goal)=>(summary[goal.status]=(summary[goal.status]??0)+1,summary),{});
let output='# Visual Instrument Roadmap\n\nVisual-session extension of Blast Radius, not an enterprise console. Status is evidence-based: shipped means implemented and checked; stubbed means a working partial surface with an unmet criterion; specified means this acceptance paragraph exists but the feature is not implemented; backlog is explicitly deferred without a current implementation. No real dataset or exclusive novelty claim is asserted.\n\n';
output+='## Status Summary\n\n'+Object.entries(counts).map(([status,count])=>`${status}: ${count}`).join('; ')+'. T1 goals: '+tier1.size+'. See UI_TEST_REPORT.md for actual executed evidence, not inferred completion.\n\n';
const themes=['Foundations','Physical Reach','Paths','Interaction','Population','Non-Human Identities','Evidence and Privacy','Teaching','Export','Quality'];
for(let theme=0;theme<10;theme++){output+=`## ${String.fromCharCode(65+theme)}. ${themes[theme]}\n\n`;for(const goal of goals.slice(theme*10,theme*10+10))output+=`### G${goal.id} ${goal.tier}: ${goal.title}\n\nStatus: **${goal.status}**. Owner: ${goal.owner}.\n\nAcceptance: ${goal.acceptance}\n\n`;}
output+='## Proposed\n\n'+proposals.map(([theme,title,acceptance,status])=>`### ${theme}: ${title}\n\n${acceptance} Status: ${status}. Owner: unassigned.\n`).join('\n');
output+='\n## Visual-Conformance Checklist\n\n- Disc area ratio and full-universe guide; zero area at zero reach.\n- Ring k equals escalation cost, not graph hops or time.\n- Fixed sensitivity bins and categorical icons/text.\n- Assumed edges dashed; missing certainty unknown.\n- Common before/after scales, population and denominator disclosures.\n- Summed versus unique reach explicitly distinguished.\n- Every view/export carries complete reproducibility stamp.\n- Keyboard evidence, focus restoration and data alternatives.\n- Reduced-motion parity; deterministic SVG bytes and reviewed screenshots.\n- Embedded fonts and tested physical figure dimensions.\n- No runtime network, telemetry, invented usage or historical rank.\n\n## Decisions for Amit\n\nRatify the visual vocabulary only after independent review; choose whether the illustrated uncertainty sidecar belongs in a future standard profile; provide approved usage/hierarchy/task-scope data before time/budget views; arrange human assistive-technology and Safari/Firefox testing where local engines are unavailable.\n';
fs.writeFileSync(path.join(root,'UI_ROADMAP.md'),output);fs.writeFileSync(path.join(root,'ui/roadmap.json'),JSON.stringify({goals,proposals,counts},null,2)+'\n');
console.log(JSON.stringify({goals:goals.length,tier1:tier1.size,counts,proposals:proposals.length}));