(function () {
  'use strict';
  const input=globalThis.BR_INPUT,V=BRVisual,esc=V.escape,$=selector=>document.querySelector(selector);
  V.configure(input.tokens,input.font);
  const models=['default','strict','session-theft-aware'];
  const titles={disc:['Credential reach','What this credential reaches'],treemap:['Population','Every credential, one common scale'],distribution:['Distribution','Where privilege accumulates'],models:['Model contrast','The cost of an assumption'],whatif:['Counterfactual','One binding. Measured consequences.'],privacy:['Privacy','The shape of a contribution'],playground:['Fixture playground','A small graph, a verifiable result'],incidents:['Public reconstructions','Evidence before interpretation'],conformance:['Conformance','The same definition, two implementations']};
  titles.lesson=['First lesson','Which access does this job need?'];
  const state={view:'lesson',model:'default',dataset:input.manifest.datasets[0],selected:null,query:'',nhi:false,redacted:false,step:null,playing:false,log:false,page:0,preview:null,baseline:null,fixture:null,incident:null,control:false,uploaded:null};
  const lesson={version:1,exercise:0,predictions:{},completed:[],evaluated:false,mode:'baseline'};
  try{const saved=JSON.parse(localStorage.getItem('br-first-lesson'));if(saved?.version===1&&Number.isInteger(saved.exercise)&&saved.exercise>=0&&saved.exercise<3&&Array.isArray(saved.completed)&&saved.completed.every(value=>[0,1,2].includes(value))){lesson.exercise=saved.exercise;lesson.completed=[...new Set(saved.completed)];for(const [key,value] of Object.entries(saved.predictions??{}))if(['0','1','2'].includes(key)&&['0','1','2'].includes(value))lesson.predictions[key]=value;}}catch{}
  const inspection=new Map(),computed=new Map();
  const drafts=new Map();
  const figureChoices={disc:[['disc','Credential reach'],['path','Explanatory path']],playground:[['disc','Credential reach'],['path','Explanatory path']],incidents:[['disc','Credential reach'],['path','Explanatory path']],treemap:[['treemap','Population']],distribution:[['lorenz','Lorenz curve'],['histogram','Histogram']],models:[['models','Model contrast']],whatif:[['whatif','Counterfactual']],privacy:[['privacy','Structural summary']],conformance:[]};
  let timer=null,currentSvg='',previousFocus=null;
  const icon=name=>input.icons[name]??input.icons['circle-info'];
  for(const [id,name] of Object.entries({redact:'eye',theme:'moon',about:'circle-info','export-svg':'file-code','export-png':'image','export-pdf':'file-pdf','close-dialog':'xmark','upload-icon':'folder-open'}))$('#'+id).innerHTML=icon(name);
  function baseResult() {
    if(state.uploaded)return state.uploaded;
    if(state.incident)return input.files[(state.control?state.incident.control_models:state.incident.models)[state.model]];
    if(state.fixture?.valid)return input.files[state.fixture.models[state.model]];
    return input.files[state.dataset.models[state.model]];
  }
  function result(){
    if(state.view==='lesson')return compute(lessonGraph(lesson.exercise===2&&lesson.mode==='least-privilege'?'baseline':lesson.evaluated?['baseline','remove','broaden'][lesson.exercise]:'baseline'),'default');
    return state.preview??baseResult();
  }
  function lessonGraph(mode='baseline'){
    const graph=structuredClone(input.files[input.manifest.fixtures.find(item=>item.id==='BR-001').graph]);
    const grant=graph.edges.find(edge=>edge.kind==='grants');
    if(mode==='remove')graph.edges=graph.edges.filter(edge=>edge.id!==grant.id);
    if(mode==='broaden')grant.actions=['read','write'];
    return graph;
  }
  function saveLesson(){try{localStorage.setItem('br-first-lesson',JSON.stringify({version:1,exercise:lesson.exercise,predictions:lesson.predictions,completed:lesson.completed}));}catch{}}
  function lessonContent(){
    const exercise=[
      {title:'One permission, four possible actions',question:'How many resource-action pairs can this credential reach?',mode:'baseline'},
      {title:'Removing required access',question:'After removing the read grant, how many pairs remain reachable?',mode:'remove'},
      {title:'Adding unnecessary access',question:'After adding write to the read grant, how many pairs become reachable?',mode:'broaden'},
    ][lesson.exercise];
    const restored=lesson.exercise===2&&lesson.mode==='least-privilege';
    const source=compute(lessonGraph(restored?'baseline':lesson.evaluated?exercise.mode:'baseline'),'default');
    const record=source.credentials[0],count=record.absolute_reach;
    const requiredMet=lesson.evaluated?exercise.mode!=='remove':true;
    const excess=lesson.evaluated&&exercise.mode==='broaden'&&!restored?1:0;
    const explanations=[
      'There are four possible resource-action pairs: read and write on each of two resources. This credential has only read on r0, so its reach is 1/4.',
      'Reach falls to 0/4, but the job can no longer read r0. Removing all access is not least privilege when it prevents required work.',
      'Reach rises to 2/4. Read on r0 is required; write on r0 is outside the stated requirement. Remove only write to preserve the required read.',
    ];
    const nodes=[['key','Credential','Alba Rune'],['link','Grant',lesson.evaluated&&exercise.mode==='remove'?'No grant':lesson.evaluated&&exercise.mode==='broaden'&&!restored?'Read + write':'Read'],['server','Resource','r0']];
    return `<div class="lesson-progress" aria-label="Lesson progress">${['Predict reach','Remove a grant','Check least privilege'].map((label,index)=>`<button type="button" data-exercise="${index}" aria-pressed="${lesson.exercise===index}">${index+1}. ${label}${lesson.completed.includes(index)?' / complete':''}</button>`).join('')}</div><section class="lesson-body" aria-labelledby="lesson-title"><div class="lesson-context"><span class="eyebrow">Fictional example / no cloud access</span><h3 id="lesson-title">${exercise.title}</h3><p>The job requires <strong>read on r0</strong>. Write on r0 and all access to r1 are outside this lesson's requirement.</p><ol class="lesson-route" aria-label="Declared access path">${nodes.map(([glyph,label,name])=>`<li>${icon(glyph)}<span>${label}</span><strong>${esc(name)}</strong></li>`).join('')}</ol><p class="lesson-universe">Inventory: r0/read, r0/write, r1/read, r1/write.</p></div><form id="lesson-form"><fieldset><legend>${exercise.question}</legend><div class="lesson-predictions">${['0','1','2'].map(value=>`<label><input type="radio" name="prediction" value="${value}" ${lesson.predictions[lesson.exercise]===value?'checked':''} required>${value} pair${value==='1'?'':'s'}</label>`).join('')}</div></fieldset><button type="submit">${icon('play')} Run ${lesson.exercise?'change':'model'}</button></form><section class="lesson-result" id="lesson-result" role="status" ${lesson.evaluated?'':'hidden'}><h3>${lesson.predictions[lesson.exercise]===String(count)?'Prediction confirmed':'Compare with your prediction'}</h3><dl><div><dt>Reach</dt><dd>${count} / ${record.universe_size}</dd></div><div><dt>Required read</dt><dd>${requiredMet?'Preserved':'Missing'}</dd></div><div><dt>Excess actions</dt><dd>${excess}</dd></div></dl><p>${explanations[lesson.exercise]}</p><p>Explain the difference between a capability, a workload requirement and a vulnerability. These results do not prove deployed access or exploitability.</p>${lesson.exercise===2?`<button type="button" id="lesson-least-privilege">${icon('minus')} Remove only write</button>`:`<button type="button" data-exercise="${lesson.exercise+1}">Next exercise ${icon('arrow-right')}</button>`}</section><p id="lesson-followup" role="status"></p><div class="lesson-links"><button type="button" id="lesson-save">${icon('download')} Export lesson progress</button><button type="button" id="lesson-reset">${icon('rotate-left')} Reset lesson</button><button type="button" data-view="playground">Open graph lab ${icon('arrow-right')}</button></div><details><summary>Independent expected answers</summary><p>Preset BR-001: 1/4. Remove read: 0/4 with required access missing. Add write: 2/4 with one unnecessary action. Remove only write: 1/4, required read preserved.</p></details></section>`;
  }
  function names(){if(!state.redacted)return{};return Object.fromEntries(result().snapshot.nodes.map(node=>[node.id,`${V.label(node.kind)} ${sha256(node.id).slice(0,8)}`]));}
  function nameOf(record){return names()[record.principal_id]??record.name;}
  function selected(){const records=result().credentials;return records.find(record=>record.credential_id===state.selected)??records[0];}
  function inspect(record=selected(),source=result()) {
    if(!record)return[];
    const key=source.snapshot_hash+':'+source.constraint_model+':'+record.credential_id;
    if(!inspection.has(key))inspection.set(key,BRReference.inspect(source.snapshot,record.credential_id,source.constraint_model));
    return inspection.get(key);
  }
  function options(){return{record:selected(),reach:state.view==='disc'||state.view==='incidents'||state.view==='playground'?inspect():[],names:names(),redacted:state.redacted,step:state.step,compact:matchMedia('(max-width:720px)').matches,approximations:state.incident?{}:state.dataset.approximation_ledger};}
  function announce(text){$('#live-status').textContent=text;}
  function parseFilter(query){
    const parts=query.trim().match(/(?:[^\s"]+|"[^"]*")+/g)??[];
    return parts.map(part=>{
      if(part.startsWith('type:')){const kind=part.slice(5);if(!input.tokens.icons[kind])throw Error('Unknown principal type');return record=>record.principal_type===kind;}
      if(part.startsWith('radius:')){const match=/^radius:([<>]=?|=)(0(?:\.\d+)?|1(?:\.0+)?)$/.exec(part);if(!match)throw Error('Radius filter requires >, >=, <, <= or = and a value from 0 to 1');return record=>({'>' :record.canonical_radius>+match[2],'>=':record.canonical_radius>=+match[2],'<':record.canonical_radius<+match[2],'<=':record.canonical_radius<=+match[2],'=':record.canonical_radius===+match[2]})[match[1]];}
      if(part==='constraint:none')return record=>(record.blocked??[]).length===0;
      if(part.includes(':'))throw Error('Unknown filter field');
      const search=part.replaceAll('"','').toLowerCase();return record=>nameOf(record).toLowerCase().includes(search);
    });
  }
  function filtered(){try{const predicates=parseFilter(state.query);$('#filter-error').textContent='';return result().credentials.filter(record=>(!state.nhi||record.principal_type!=='human_user')&&predicates.every(test=>test(record)));}catch(error){$('#filter-error').textContent=error.message;return[];}}
  function stats(records){const values=records.map(record=>record.canonical_radius).sort((left,right)=>left-right),count=values.length;return{count,median:count?(count%2?values[Math.floor(count/2)]:(values[count/2-1]+values[count/2])/2):null,p95:count?values[Math.ceil(count*.95)-1]:null};}
  function comparisonMini(){const all=result().credentials,human=stats(all.filter(record=>record.principal_type==='human_user')),nhi=stats(all.filter(record=>record.principal_type!=='human_user'));return `<div class="compare-mini"><div><span>Human / ${human.count}</span><strong>${V.percent(human.median)}</strong><span>median / p95 ${V.percent(human.p95)}</span></div><div><span>Non-human / ${nhi.count}</span><strong>${V.percent(nhi.median)}</strong><span>median / p95 ${V.percent(nhi.p95)}</span></div></div>`;}
  function sidebar(){
    const records=filtered(),perPage=50,totalPages=Math.max(1,Math.ceil(records.length/perPage));state.page=Math.min(state.page,totalPages-1);
    $('#credential-count').textContent=records.length+'/'+result().credentials.length;
    $('#credential-toggle').innerHTML=`${esc(selected()?nameOf(selected()).replace(/^Fictional /,''):'Choose credential')} ${icon('bars')}`;
    $('#identity-comparison').innerHTML=comparisonMini();
    $('#credential-list').innerHTML=records.slice(state.page*perPage,(state.page+1)*perPage).map(record=>`<button class="credential-button" data-select="${esc(record.credential_id)}" aria-pressed="${record.credential_id===selected()?.credential_id}"><span style="color:${input.tokens.color.categorical[record.principal_type]}">${icon(input.tokens.icons[record.principal_type])}</span><span class="name">${esc(nameOf(record).replace(/^Fictional /,''))}<small>${esc(V.label(record.principal_type))}</small></span><span class="radius">${(record.canonical_radius*100).toFixed(1)}<small>${record.absolute_reach} pairs</small></span></button>`).join('')||'<p class="empty">No matching credentials</p>';
    $('#list-pagination').innerHTML=totalPages>1?`<button data-page="-1" aria-label="Previous credential page" ${state.page===0?'disabled':''}>${icon('arrow-left')}</button><span>${state.page+1} / ${totalPages}</span><button data-page="1" aria-label="Next credential page" ${state.page===totalPages-1?'disabled':''}>${icon('arrow-right')}</button>`:'';
  }
  const definitions={canonical_radius:['BR-R20','|reachable resource-action pairs| / |full declared universe|','src/blastradius/analysis.py: Analysis.credential'],sensitivity_weighted_radius:['BR-R21','Sum of reachable resource sensitivities / sum over all resource-action pairs. Weights are a policy choice.','src/blastradius/analysis.py: Analysis.credential'],action_weighted_radius:['BR-R22','Sum of reachable action weights / sum over the same full inventory.','src/blastradius/analysis.py: Analysis.credential'],step_bounded_radius:['BR-R23','Pairs whose shortest escalation cost is at most k / the full universe. Ordinary graph hops do not count as escalation.','src/blastradius/engine.py: Engine.reach'],absolute_reach:['BR-R03 / BR-R20','Unique reachable (resource, action) pairs. Multiple paths do not multiply the count.','src/blastradius/engine.py: Reach.pairs'],distribution:['BR-R25','Nearest-rank p95, sorted-value Gini and strictly-above-threshold share. Summed reach across credentials may count the same resource-action pair repeatedly.','src/blastradius/analysis.py: distribution']};
  function metricRows(record=selected(),source=result()){
    if(!record)return[];
    const exact=record.exact??{};
    let bounded='Undefined pair ratio';
    if(exact.bounded!=null){const [numerator,denominator='1']=exact.bounded.split('/');bounded=`${BigInt(numerator)*BigInt(record.universe_size)/BigInt(denominator)} / ${record.universe_size} pairs`;}
    return[
      ['canonical_radius','Canonical',V.percent(record.canonical_radius),`${record.absolute_reach} / ${record.universe_size} pairs`],
      ['sensitivity_weighted_radius','Sensitivity',V.percent(record.sensitivity_weighted_radius),exact.sensitivity==null?'Undefined: total sensitivity is zero':`Exact weighted ratio ${exact.sensitivity}`],
      ['action_weighted_radius','Action weighted',V.percent(record.action_weighted_radius),exact.action==null?'Undefined: total action weight is zero':`Exact weighted ratio ${exact.action}`],
      ['step_bounded_radius',`Bounded / k${source.parameters.step_bound}`,V.percent(record.step_bounded_radius),bounded],
      ['absolute_reach','Absolute reach',record.absolute_reach,'Unique resource-action pairs'],
    ];
  }
  function metrics(){$('#metric-strip').innerHTML=metricRows().map(([field,title,value,caption])=>`<button data-definition="${field}"><span>${esc(title)}</span><strong>${esc(value)}</strong><small>${esc(caption)}</small></button>`).join('');}
  function table(records=filtered(),comparison){const original=new Map((comparison?.credentials??[]).map(record=>[record.credential_id,record]));return `<div class="table-scroll"><table><caption>${records.length} credentials. First 200 rows displayed; filtered JSON available in the evidence drawer.</caption><thead><tr><th>Credential</th><th>Type</th><th class="number">Pairs / U</th><th class="number">Canonical</th><th class="number">Sensitivity</th><th class="number">Action</th><th class="number">Bounded</th>${comparison?'<th class="number">Delta / pp</th>':''}</tr></thead><tbody>${records.slice(0,200).map(record=>`<tr><td><button data-select="${esc(record.credential_id)}">${esc(nameOf(record))}</button></td><td>${esc(V.label(record.principal_type))}</td><td class="number">${record.absolute_reach}/${record.universe_size}</td><td class="number">${V.percent(record.canonical_radius)}</td><td class="number">${V.percent(record.sensitivity_weighted_radius)}</td><td class="number">${V.percent(record.action_weighted_radius)}</td><td class="number">${V.percent(record.step_bounded_radius)}</td>${comparison?`<td class="number">${((record.canonical_radius-(original.get(record.credential_id)?.canonical_radius??0))*100).toFixed(2)}</td>`:''}</tr>`).join('')}</tbody></table></div>`;}
  function legend(){return `<div class="chart-legend">${Object.entries(input.tokens.color.categorical).filter(([kind])=>kind!=='group').map(([kind,color])=>`<span><i class="swatch" style="background:${color}"></i>${esc(V.label(kind))}</span>`).join('')}</div>`;}
  function showEvidence(title,body){previousFocus=document.activeElement;$('#evidence-title').textContent=title;$('#evidence-body').innerHTML=body;$('#evidence-dialog').showModal();$('#close-dialog').focus();}
  function definition(field){const [clause,formula,code]=definitions[field]??definitions.distribution;showEvidence('Definition / '+clause,`<p class="formula">${esc(formula)}</p><p>Code: <code>${esc(code)}</code></p><p><a href="../spec/METRIC_SPECIFICATION_v1.0-draft.md" target="_blank" rel="noopener">Metric Specification v1.0-draft</a></p><pre class="json">${esc(JSON.stringify(selected(),null,2))}</pre>`);}
  function nodeEvidence(id,action){const graph=result().snapshot,node=graph.nodes.find(node=>node.id===id),edge=graph.edges.find(edge=>edge.id===id),item=node??edge;if(!item)return;const provenance=item.provenance??{};showEvidence(names()[id]??item.name??'Transition evidence',`<p>${esc(V.label(item.kind))}${action?' / '+esc(action):''}</p><dl>${Object.entries(provenance).map(([key,value])=>`<dt>${esc(V.label(key))}</dt><dd>${esc(value)}</dd>`).join('')}</dl>${node?.kind==='resource'?`<p>Sensitivity ${node.sensitivity}; supported actions: ${esc(node.actions.join(', '))}.</p>`:''}${node?.kind==='binding'?`<button data-remove="${esc(id)}">${icon('minus')} Remove this binding</button>`:''}<pre class="json">${esc(JSON.stringify(item,null,2))}</pre>`);}
  function svg(view=state.view,extra={}){const source=result(),opts={...options(),records:filtered(),log:state.log,...extra};if(view==='disc'||view==='incidents'||view==='playground')return V.disc(source,opts);if(view==='path')return V.pathView(source,opts);if(view==='treemap')return V.treemap(source,opts);if(view==='lorenz'||view==='distribution')return V.lorenz(source,opts);if(view==='histogram')return V.histogram(source,opts);if(view==='models')return V.comparison(input.files[state.dataset.models.default],source,{...opts,title:'Constraint-model contrast',view:'models'});if(view==='whatif')return V.comparison(state.baseline??baseResult(),source,opts);if(view==='privacy')return V.silhouette(source,summary(),opts);return V.disc(source,opts);}
  function summary(){const source=result(),nodes=source.snapshot.nodes,edges=source.snapshot.edges,bindings=new Map();for(const edge of edges)if(edge.kind==='assigned'){if(!bindings.has(edge.target))bindings.set(edge.target,new Set());bindings.get(edge.target).add(edge.source);}const histogram=Array(10).fill(0);for(const record of source.credentials)histogram[Math.min(9,Math.floor(record.absolute_reach*10/record.universe_size))]++;const kinds=['principal','credential','binding','resource','constraint'],principals=['human_user','service_principal','managed_identity','workload_identity','ai_agent','group'],credentials=['password','key','certificate','token','passkey','federated_trust'],relations=['authenticates_as','member_of','assigned','grants','can_assume','can_read_secret','constrained_by'];return{summary_version:'1.0-draft',synthetic:true,submission_enabled:false,privacy_reviewed:false,anonymous:false,schema_version:'0.1',metric_profile:'1.0-draft',normalizer_profile:'unasserted',constraint_model:source.constraint_model,action_profile:BRReference.canonical(source.snapshot.action_weights)===BRReference.canonical({read:1,write:3,administer:5,read_metadata:1,read_secret:1})?'core-1-3-5':'custom-not-comparable',node_counts:Object.fromEntries(kinds.map(kind=>[kind,nodes.filter(node=>node.kind===kind).length])),principal_counts:Object.fromEntries(principals.map(kind=>[kind,nodes.filter(node=>node.kind==='principal'&&node.subtype===kind).length])),credential_counts:Object.fromEntries(credentials.map(kind=>[kind,nodes.filter(node=>node.kind==='credential'&&node.subtype===kind).length])),edge_counts:Object.fromEntries(relations.map(kind=>[kind,edges.filter(edge=>edge.kind===kind).length])),structural_features:{shared_binding_count:[...bindings.values()].filter(group=>group.size>1).length,eligible_binding_count:nodes.filter(node=>node.eligible).length,constrained_item_count:new Set([...nodes,...edges].filter(item=>item.constraints?.length).map(item=>item.id).concat(edges.filter(edge=>edge.kind==='constrained_by').map(edge=>edge.source))).size},canonical_radius_histogram:histogram.map((count,index)=>({lower:index/10,upper:(index+1)/10,upper_inclusive:index===9,count}))};}
  function playback(){const reach=inspect(),maximum=Math.max(0,...reach.map(item=>item.rank[0]));if(state.step==null)state.step=maximum;return `<div class="playback"><button id="play" class="icon-button" aria-label="${state.playing?'Pause propagation':'Play propagation'}" title="${state.playing?'Pause':'Play'}">${icon(state.playing?'pause':'play')}</button><button id="step-back" class="icon-button" aria-label="Previous escalation step" title="Previous step">${icon('backward-step')}</button><button id="step-next" class="icon-button" aria-label="Next escalation step" title="Next step">${icon('forward-step')}</button><input id="step-range" type="range" min="0" max="${maximum}" step="1" value="${state.step}" aria-label="Escalation step"><output id="step-output">Step ${state.step} of ${maximum}</output></div>`;}
  function uncertainty(){const record=selected();if(!record)return'';if(state.incident)return '<p class="notice">Evidence: public mechanism reconstruction. Every unreported graph detail is an assumption; historical rank is unidentifiable.</p>';if(state.uploaded||state.fixture||state.preview)return '<p class="notice">Approximation share: unknown. This result does not supply an approximation ledger.</p>';const without=input.files[state.dataset.without_approximations[state.model]].credentials.find(item=>item.credential_id===record.credential_id),lost=record.absolute_reach-without.absolute_reach;return `<p class="notice">Illustrative certainty test: <strong>${lost}/${record.absolute_reach} pairs (${record.absolute_reach?V.percent(lost/record.absolute_reach):'undefined'})</strong> disappear when the declared assumed trust is removed. Dashed path segments mark that assumption. This is not empirical confidence.</p>`;}
  function narrative(){
    const source=result(),record=selected(),labels=names();
    const lines=['Blast Radius / Credential evidence','Illustrative / synthetic. No live-tenant assessment is claimed.',state.redacted?'Deterministic display pseudonyms enabled. Provenance references are retained; this is not anonymous.':'Original synthetic names.',`Snapshot SHA-256: ${source.snapshot_hash}`,`Model: ${source.constraint_model}`,`Engine: ${source.engine_version}`,`Schema: ${source.schema_version}`,`Step bound: ${source.parameters.step_bound}; threshold: ${source.parameters.threshold}`,`Generated: ${source.generated_at}`,`Manifest: ${source.manifest_hash??'Not supplied'}`,'Manifest verification is not performed by this viewer.'];
    if(state.preview)lines.push('Local counterfactual only. No platform change was executed.');
    if(state.incident)lines.push('Public mechanism reconstruction. Historical rank is not identifiable.');
    if(!record)return lines.concat('No credential selected.').join('\n');
    lines.push(`Principal: ${nameOf(record)}`,`Credential type: ${V.label(record.credential_type)}`);
    for(const [,title,value,caption] of metricRows(record,source))lines.push(`${title}: ${value} (${caption})`);
    if(record.explanation){
      lines.push(`Explanatory path: ${record.explanation.escalation_steps} escalation steps / ${record.explanation.graph_hops} graph hops / ${record.explanation.action}`);
      for(const [index,edge] of record.explanation.steps.entries()){
        lines.push(`${index+1}. ${labels[edge.source]??edge.source_name??edge.source} --${edge.kind}--> ${labels[edge.target]??edge.target_name??edge.target}.`,`   Transition: ${edge.id}`);
        for(const [field,value] of Object.entries(edge.provenance))lines.push(`   ${V.label(field)}: ${value}`);
      }
    }else lines.push('No reachable explanatory path under the selected model.');
    for(const item of record.blocked??[])lines.push(`${item.edge_id}: ${item.reason}${item.details?.length?' / '+item.details.join(', '):''}`);
    return lines.join('\n');
  }
  async function copyNarrative(){
    const content=narrative();
    try{if(typeof navigator.clipboard?.writeText!=='function')throw Error('Clipboard unavailable');await navigator.clipboard.writeText(content);announce('Evidence narrative copied');return true;}
    catch{showEvidence('Evidence narrative',`<textarea id="narrative-copy" class="json" rows="12" readonly aria-label="Evidence narrative">${esc(content)}</textarea>`);$('#narrative-copy').focus();$('#narrative-copy').select();announce('Automatic copy unavailable. Evidence selected for manual copying.');return false;}
  }
  function discContent(){return `<div class="chart-shell" id="primary-chart">${svg('disc')}</div>${playback()}<div class="pair-info" id="pair-info" role="status">${selected()?`${selected().absolute_reach} reachable pairs in a ${selected().universe_size}-pair universe.`:'No credential selected.'}</div>${uncertainty()}<div class="view-subheading"><h3>Explanatory path</h3><button id="copy-narrative">${icon('copy')} Copy evidence narrative</button></div><div class="chart-shell">${svg('path')}</div><details><summary>Path narrative</summary><pre class="json">${esc(narrative())}</pre></details>${(selected()?.blocked??[]).length?`<details><summary>${selected().blocked.length} blocked transitions</summary>${selected().blocked.map(item=>`<p class="barrier"><button data-node="${esc(item.edge_id)}">${esc(item.reason)} / ${esc(item.edge_id)}</button></p>`).join('')}</details>`:''}`;}
  function miniDisc(value,labelText){const radius=31*Math.sqrt(value??0);return `<div class="mini-disc"><svg viewBox="0 0 70 70" role="img" aria-label="${esc(labelText+' '+V.percent(value))}"><circle cx="35" cy="35" r="31" fill="none" stroke="#aab7bd" stroke-dasharray="3 3"/><circle cx="35" cy="35" r="${radius.toFixed(3)}" fill="#dce7ed" stroke="#344b56"/></svg><span>${labelText} ${V.percent(value)}</span></div>`;}
  function counterCards(){return `<div class="cards">${(baseResult().recommendations??[]).slice(0,5).map(change=>`<article class="counter-card"><h3>${esc(change.name)}</h3><div class="mini-discs">${miniDisc(change.before_p95,'Before')}${miniDisc(change.after_p95,'After')}</div><p>Canonical p95 / ${change.absolute_pairs_removed} credential-pair exposures removed / ${change.evaluated_candidates} candidates evaluated.</p><button data-remove="${esc(change.binding_id)}">${icon('minus')} Preview removal</button></article>`).join('')||'<p class="notice">No ranked single-binding evaluations are supplied for this result.</p>'}</div>`;}
  function whatifContent(){const source=result(),bindings=baseResult().snapshot.nodes.filter(node=>node.kind==='binding');return `<div class="controls"><label for="binding-select">Binding<select id="binding-select">${bindings.map(node=>`<option value="${esc(node.id)}">${esc(names()[node.id]??node.name)}</option>`).join('')}</select></label><button id="remove-selected">${icon('minus')} Remove</button><button id="add-binding">${icon('plus')} Add binding</button><button id="reset-whatif">${icon('rotate-left')} Restore snapshot</button></div><p class="notice">Local counterfactual only. No platform change is executed. Deleting a deny can increase reach.</p><div class="chart-shell">${svg('whatif')}</div>${tenantDelta()}<div class="view-subheading"><h3>Five evaluated single changes</h3></div>${counterCards()}`;}
  function tenantDelta(){const before=(state.view==='models'?input.files[state.dataset.models.default]:(state.baseline??baseResult())).statistics.canonical_radius,after=result().statistics.canonical_radius;return `<table><caption>Canonical tenant statistics / after minus before</caption><thead><tr><th>Statistic</th><th>Before</th><th>After</th><th>Delta</th></tr></thead><tbody>${['max','p95','gini','share_above_threshold'].map(key=>`<tr><td>${esc(key)}</td><td>${before[key]==null?'undefined':before[key].toFixed(4)}</td><td>${after[key]==null?'undefined':after[key].toFixed(4)}</td><td>${after[key]==null?'undefined':(after[key]-before[key]).toFixed(4)}</td></tr>`).join('')}</tbody></table>`;}
  function privacyContent(){const payload=summary(),analysis=input.files[input.manifest.privacy_analysis];return `<div class="chart-shell">${svg('privacy')}</div><p class="notice"><strong>Not anonymous.</strong> The prior synthetic privacy experiment found ${analysis.exact_summary.unique_rows}/${analysis.tenants} exact summaries unique. This does not estimate real-company re-identification probability.</p><details open><summary>Exact local payload JSON</summary><pre class="json">${esc(JSON.stringify(payload,null,2))}</pre></details><div class="key-value"><section><h3>Payload</h3><p>Fixed structural counts and histogram; no names, IDs, paths, hashes or timestamps.</p></section><section><h3>Stays local</h3><p>Full snapshot, credentials metadata, paths, provenance, weights and result details. No network submission exists.</p></section></div>`;}
  function playgroundContent(){const fixture=state.fixture??input.manifest.fixtures[0];return `<div class="controls"><label for="fixture-select">Conformance preset<select id="fixture-select">${input.manifest.fixtures.map(item=>`<option value="${item.id}" ${item.id===fixture.id?'selected':''}>${item.id} / ${esc(item.title)}${item.valid?'':' / invalid'}</option>`).join('')}</select></label><button id="evaluate">${icon('play')} Evaluate</button><button data-edit="node" title="Add resource node">${icon('plus')} Node</button><button data-edit="edge" title="Add a grant edge">${icon('link')} Edge</button><button data-edit="constraint" title="Add device constraint">${icon('shield')} Constraint</button><button id="reset-playground" title="Reset edited graph">${icon('rotate-left')} Reset preset</button></div><p id="draft-status" class="notice" role="status">${drafts.has(fixture.id)?'Edited graph / unsaved':'Original preset'} / ${esc(state.model)}</p><div class="editor-grid"><div><label for="graph-editor">Graph JSON</label><textarea id="graph-editor" spellcheck="false">${esc(drafts.get(fixture.id)??JSON.stringify(input.files[fixture.graph],null,2))}</textarea><p id="editor-error" class="error" role="status"></p></div><div><h3>Preset derivation / ${fixture.id}</h3><p>${esc(fixture.derivation)}</p><p>${fixture.requirements.map(esc).join(', ')}</p><div id="playground-outcome">${selected()?`${selected().absolute_reach} / ${selected().universe_size} = ${V.percent(selected().canonical_radius)}`:'No valid result'}</div></div></div><div class="chart-shell">${svg('playground')}</div>`;}
  function incidentsContent(){const incident=state.incident??input.manifest.incidents[0];return `<select class="incident-select" id="incident-select" aria-label="Public incident reconstruction">${input.manifest.incidents.map(item=>`<option value="${item.id}" ${item.id===incident.id?'selected':''}>${esc(item.title)}</option>`).join('')}</select><p class="notice">${esc(incident.evidence.grade)}. Historical rank: <strong>not identifiable</strong>; the full preincident population is unavailable.</p><p>${esc(incident.evidence.narrative)}</p><label class="check"><input type="checkbox" id="incident-control" ${state.control?'checked':''}>Apply hypothetical ${esc(incident.evidence.control)} control</label><div class="chart-shell">${svg('incidents')}</div><div class="chart-shell">${svg('path')}</div><details open><summary>Assumptions ledger</summary><ol class="assumption-list">${incident.evidence.assumptions.map(value=>`<li>${esc(value)}</li>`).join('')}</ol><p>${esc(incident.evidence.boundary)}</p></details><details><summary>Public source evidence</summary>${incident.evidence.sources.map(source=>`<p><a href="${esc(source.url)}" target="_blank" rel="noopener">${esc(source.title)}</a> / ${esc(source.publisher)} / ${esc(source.date)}</p>`).join('')}</details>`;}
  function conformanceContent(){const reports=Object.entries(input.manifest.conformance_reports).map(([name,file])=>[name,input.files[file]]);return `<p class="notice">Saved public core reports. Passing a finite corpus is not certification, provider completeness, or independent authorship.</p><table><caption>Requirement-by-implementation results</caption><thead><tr><th>Requirement</th>${reports.map(([name])=>`<th>${name}</th>`).join('')}</tr></thead><tbody>${Array.from({length:32},(_,index)=>`BR-R${String(index+1).padStart(2,'0')}`).map(rule=>`<tr><td><button data-rule="${rule}">${rule}</button></td>${reports.map(([,report])=>`<td>${report.requirements[rule]==='pass'?'PASS':'Manual / not automated'}</td>`).join('')}</tr>`).join('')}</tbody></table>`;}
  function updateURL(){const params=new URLSearchParams({view:state.view,snapshot:result().snapshot_hash,model:state.view==='lesson'?'default':state.model,item:String(result().credentials.findIndex(record=>record.credential_id===selected()?.credential_id)),lens:state.nhi?'nhi':'all'});try{history.replaceState(null,'','#'+params);}catch{}}
  function updateExportControls(){
    const choices=state.editorInvalid?[]:figureChoices[state.view]??[];
    if(!choices.some(([kind])=>kind===state.figure))state.figure=choices[0]?.[0]??null;
    const picker=$('#figure-kind');
    picker.innerHTML=choices.length?choices.map(([kind,label])=>`<option value="${kind}" ${kind===state.figure?'selected':''}>${esc(label)}</option>`).join(''):'<option value="">No exportable figure</option>';
    picker.disabled=choices.length<2;$('#column-width').disabled=!choices.length;
    for(const format of ['svg','png','pdf'])$('#export-'+format).disabled=!choices.length;
  }
  function render(){
    const focused=document.activeElement,focusKey=focused?.id?'#'+CSS.escape(focused.id):focused?.dataset?.model?'[data-model="'+focused.dataset.model+'"]':focused?.dataset?.select?'[data-select="'+CSS.escape(focused.dataset.select)+'"]':null;
    const source=result(),record=selected();if(record)state.selected=record.credential_id;
    document.body.classList.toggle('lesson-mode',state.view==='lesson');
    document.title=state.view==='lesson'?'Blast Radius | First lesson':`Blast Radius | ${state.redacted?'Illustrative snapshot':source.organization}`;
    $('#dataset-title').textContent=state.redacted?'Illustrative snapshot':source.organization.replace(/^Fictional /,'');
    $('#view-kicker').textContent=titles[state.view][0];$('#view-heading').textContent=titles[state.view][1];
    document.querySelectorAll('[data-view]').forEach(button=>{if(button.tagName==='BUTTON'){if(button.dataset.view===state.view)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current');}});
    document.querySelectorAll('[data-model]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.model===state.model)));
    sidebar();metrics();
    let content='';
    if(state.view==='lesson')content=lessonContent();
    if(state.view==='disc')content=discContent();
    if(state.view==='treemap')content=filtered().length>1500?`${legend()}<p class="notice">${filtered().length>10000?'Aggregated by principal type and fixed 0.05 radius bins. Area is summed absolute reach; no individual ranking is implied.':'One canvas rectangle per positive-reach credential. Area = absolute reach. The searchable table is the keyboard alternative.'}</p><div class="canvas-shell"><canvas id="population-canvas" aria-label="Credential population canvas"></canvas><canvas id="population-overlay" tabindex="0" role="button" aria-label="Select highlighted credential; use the credential table for complete keyboard selection"></canvas></div><p id="canvas-info" class="notice" role="status"></p>`:`${legend()}<div class="chart-shell">${svg('treemap')}</div>`;
    if(state.view==='distribution')content=`${legend()}<div class="chart-shell">${svg('lorenz')}</div><div class="controls"><label class="check"><input type="checkbox" id="log-scale" ${state.log?'checked':''}>Log(1 + count)</label></div><div class="chart-shell">${svg('histogram')}</div><p class="notice">Overlapping credential reach is summed for the Lorenz curve. It is not the union of exposed tenant resources.</p>`;
    if(state.view==='models')content=`<p class="notice">Default is the fixed comparison baseline. Model assumptions change permission reach, not incident probability.</p><div class="chart-shell">${svg('models')}</div>${tenantDelta()}`;
    if(state.view==='whatif')content=whatifContent();
    if(state.view==='privacy')content=privacyContent();
    if(state.view==='playground')content=playgroundContent();
    if(state.view==='incidents')content=incidentsContent();
    if(state.view==='conformance')content=conformanceContent();
    $('#view-content').innerHTML=content;
    document.querySelectorAll('pre.json,.table-scroll').forEach(element=>element.tabIndex=0);
    if(state.view==='treemap'&&filtered().length>1500){const evidence=BRPopulation.mount($('#population-canvas'),$('#population-overlay'),source,filtered(),input.tokens,(item,aggregated)=>{if(aggregated){state.query='type:'+item.principal_type;$('#search').value=state.query;state.page=0;render();}else{state.selected=item.credential_id;state.view='disc';state.step=null;render();}});$('#canvas-info').textContent=`${evidence.credential_count} credentials / ${evidence.rendered_marks} marks / ${evidence.aggregated?'aggregated':'individual'} canvas`;currentSvg='';}else currentSvg=svg();
    const before=state.view==='models'?input.files[state.dataset.models.default]:state.baseline;
    $('#data-table').innerHTML=table(filtered(),before);
    $('#computation').innerHTML=Object.entries(definitions).map(([key,[clause,formula,code]])=>`<p><button data-definition="${key}">${clause}</button> ${esc(formula)} <code>${esc(code)}</code></p>`).join('');
    $('#stamp').innerHTML=`<p>Illustrative / synthetic. ${esc(state.redacted?'Deterministic pseudonyms enabled':'Original synthetic names')}. No telemetry or submission.</p><p>Snapshot ${source.snapshot_hash}</p><p>Engine ${esc(source.engine_version)} / schema ${esc(source.schema_version)} / ${esc(source.constraint_model)} / k=${source.parameters.step_bound} / threshold=${esc(source.parameters.threshold)} / generated ${esc(source.generated_at)}</p><p>${esc(input.tokens.version)} / manifest ${source.manifest_hash} / local HMAC not verified by this viewer.</p>`;
    state.editorInvalid=state.view==='playground'&&state.fixture?.valid===false&&!state.preview;
    if(state.editorInvalid){$('#metric-strip').innerHTML='';$('#data-table').innerHTML='<p>No result: this preset is invalid.</p>';$('#playground-outcome').textContent='No score: invalid conformance preset';$('#view-content .chart-shell').innerHTML='<p class="empty">Invalid input. No radius or witness is rendered.</p>';$('#stamp').textContent=`${state.fixture.id} / invalid input; no engine result or figure exists.`;}
    if(state.view==='playground'&&drafts.has(state.fixture?.id))evaluate();
    updateExportControls();updateURL();
    if(focusKey)document.querySelector(focusKey)?.focus({preventScroll:true});
    announce(`${titles[state.view][0]}. ${record?`${record.absolute_reach} of ${record.universe_size} pairs.`:'No credentials.'}`);
  }
  function selectView(view){stop();if(state.view==='playground'&&state.fixture&&$('#graph-editor'))drafts.set(state.fixture.id,$('#graph-editor').value);state.view=view;if(view==='playground'&&!state.fixture){state.fixture=input.manifest.fixtures[0];state.incident=null;state.preview=null;}else if(view==='incidents'&&!state.incident){state.incident=input.manifest.incidents[0];state.fixture=null;state.preview=null;}else if(!['playground','incidents'].includes(view)&&(state.fixture||state.incident)){state.fixture=null;state.incident=null;state.control=false;state.preview=null;}state.step=null;render();}
  function stop(){clearInterval(timer);timer=null;state.playing=false;}
  function scrub(step){state.step=Math.max(0,Math.min(Math.max(0,...inspect().map(item=>item.rank[0])),step));$('#primary-chart').innerHTML=svg('disc');$('#step-range').value=state.step;$('#step-output').textContent=`Step ${state.step} of ${$('#step-range').max}`;announce(`${inspect().filter(item=>item.rank[0]<=state.step).length} pairs through step ${state.step}`);}
  function play(){if(state.playing){stop();$('#play').innerHTML=icon('play');$('#play').setAttribute('aria-label','Play propagation');return;}if(matchMedia('(prefers-reduced-motion: reduce)').matches){scrub(Math.max(0,...inspect().map(item=>item.rank[0])));announce('Reduced motion: all escalation steps shown. Manual scrub remains available.');return;}state.playing=true;scrub(0);$('#play').innerHTML=icon('pause');$('#play').setAttribute('aria-label','Pause propagation');timer=setInterval(()=>{const maximum=Math.max(0,...inspect().map(item=>item.rank[0]));if(state.step>=maximum){stop();$('#play').innerHTML=icon('play');$('#play').setAttribute('aria-label','Play propagation');}else scrub(state.step+1);},input.tokens.motion.stepMs);}
  function compute(graph,model=state.model){
    if(graph.nodes.length>1000)throw Error('Interactive recomputation is limited to 1000 nodes; import precomputed large results for population rendering.');
    const request={contract_version:'1.0-draft',input:graph,parameters:{constraint_model:model,step_bound:1,threshold:'1/4'}},response=BRReference.fromText(JSON.stringify(request));
    if(response.status!=='ok')throw Error('Graph rejected by the reference engine. No score is produced.');
    const nodes=new Map(graph.nodes.map(node=>[node.id,node])),edges=new Map(graph.edges.map(edge=>[edge.id,edge]));
    const records=response.credentials.map(item=>{const credential=nodes.get(item.credential_id),principal=nodes.get(credential.principal_id),witness=item.witness;return{credential_id:item.credential_id,principal_id:principal.id,name:principal.name,principal_type:principal.subtype,credential_type:credential.subtype,absolute_reach:item.absolute_reach,universe_size:item.universe_size,canonical_radius:V.numeric(item.canonical_radius),sensitivity_weighted_radius:V.numeric(item.sensitivity_weighted_radius),action_weighted_radius:V.numeric(item.action_weighted_radius),step_bounded_radius:V.numeric(item.step_bounded_radius),exact:{canonical:item.canonical_radius,sensitivity:item.sensitivity_weighted_radius,action:item.action_weighted_radius,bounded:item.step_bounded_radius},blocked:[],explanation:witness?{resource_id:witness.resource_id,resource_name:nodes.get(witness.resource_id).name,action:witness.action,escalation_steps:witness.escalation_steps,graph_hops:witness.graph_hops,steps:witness.edge_ids.map(id=>{const edge=edges.get(id);return{...edge,source_name:nodes.get(edge.source).name,target_name:nodes.get(edge.target).name};})}:null};}).sort((left,right)=>right.canonical_radius-left.canonical_radius||left.credential_id.localeCompare(right.credential_id));
    const statistics=Object.fromEntries(Object.entries(response.statistics).map(([field,entry])=>[field,{count:entry.credential_count,max:V.numeric(entry.maximum),p95:V.numeric(entry.p95),gini:V.numeric(entry.gini),share_above_threshold:V.numeric(entry.share_above_threshold),median:stats(records.map(record=>({...record,canonical_radius:record[field]}))).median}]));
    const output={format_version:'0.1',synthetic:true,organization:graph.organization,snapshot_hash:response.snapshot_hash,schema_version:graph.schema_version,engine_version:'0.1.0-js-reference',constraint_model:model,parameters:{step_bound:1,threshold:'1/4',path_limit:100},generated_at:graph.observed_at,time_basis:'snapshot observed_at, not browser time',universe_size:records[0]?.universe_size??graph.nodes.filter(node=>node.kind==='resource').reduce((total,node)=>total+node.actions.length,0),credentials:records,statistics,by_type:{},coverage:graph.coverage,recommendations:[],recommendation_status:'not requested',snapshot:graph};output.manifest_hash=sha256(BRReference.canonical(output));return output;
  }
  async function removeBinding(id){try{announce('Computing local counterfactual');const before=baseResult(),graph=structuredClone(before.snapshot),node=graph.nodes.find(node=>node.id===id);if(node?.kind!=='binding')throw Error('Select a binding.');const removed=graph.edges.filter(edge=>edge.source===id||edge.target===id).map(edge=>edge.id);graph.nodes=graph.nodes.filter(node=>node.id!==id);graph.edges=graph.edges.filter(edge=>edge.source!==id&&edge.target!==id&&!removed.includes(edge.source));const key=before.snapshot_hash+state.model+id;if(!computed.has(key))computed.set(key,compute(graph));state.baseline=before;state.preview=computed.get(key);state.view='whatif';$('#evidence-dialog').close();render();}catch(error){showEvidence('Counterfactual rejected',`<p>${esc(error.message)}</p>`);}}
  function addBinding(){const graph=baseResult().snapshot,principals=graph.nodes.filter(node=>node.kind==='principal'&&node.subtype!=='group'),resources=graph.nodes.filter(node=>node.kind==='resource');showEvidence('Add a hypothetical binding',`<form id="add-form"><label>Principal<select id="add-principal">${principals.map(node=>`<option value="${esc(node.id)}">${esc(names()[node.id]??node.name)}</option>`).join('')}</select></label><label>Resource<select id="add-resource">${resources.map(node=>`<option value="${esc(node.id)}">${esc(names()[node.id]??node.name)}</option>`).join('')}</select></label><label>Action<select id="add-action"><option>read</option><option>write</option><option>administer</option><option>read_secret</option><option>read_metadata</option></select></label><p>Only actions declared by the selected resource are accepted.</p><button type="submit">Evaluate binding</button></form>`);}
  function editGraph(kind){try{const graph=JSON.parse($('#graph-editor').value),provenance={connector:'visual-playground',source_api:'explicit synthetic edit',observed_at:graph.observed_at,evidence_ref:'local-edit'},number=graph.nodes.length+graph.edges.length;
    if(kind==='node')graph.nodes.push({id:'local-resource-'+number,kind:'resource',subtype:'collection',name:'Fictional added resource',actions:['read'],sensitivity:.5,provenance});
    if(kind==='edge'){const binding=graph.nodes.find(node=>node.kind==='binding'&&node.effect==='allow'),resource=graph.nodes.filter(node=>node.kind==='resource').at(-1);if(!binding||!resource)throw Error('A binding and resource are required.');graph.edges.push({id:'local-grant-'+number,kind:'grants',source:binding.id,target:resource.id,actions:[resource.actions[0]],provenance});}
    if(kind==='constraint'){const binding=graph.nodes.find(node=>node.kind==='binding'&&node.effect==='allow');if(!binding)throw Error('An allow binding is required.');const id='local-device-'+number;graph.nodes.push({id,kind:'constraint',subtype:'device_required',name:'Fictional device requirement',provenance});binding.constraints.push(id);}
    $('#graph-editor').value=JSON.stringify(graph,null,2);evaluate();}catch(error){$('#editor-error').textContent=error.message;}}
  function evaluate(){const raw=$('#graph-editor').value;drafts.set(state.fixture.id,raw);try{const graph=JSON.parse(raw);if(graph.nodes.length>200)throw Error('Playground limit: 200 nodes.');state.preview=compute(graph);state.editorInvalid=false;state.selected=state.preview.credentials[0]?.credential_id;metrics();sidebar();$('#view-content .chart-shell').innerHTML=svg('playground');$('#editor-error').textContent='Valid edited graph. Preset derivation applies only to the unchanged preset.';$('#playground-outcome').textContent=selected()?`${selected().absolute_reach}/${selected().universe_size} = ${V.percent(selected().canonical_radius)}`:'Empty credential population';$('#data-table').innerHTML=table();$('#stamp').textContent=V.stamp(result());}catch(error){state.editorInvalid=true;$('#metric-strip').innerHTML='';$('#view-content .chart-shell').innerHTML='<p class="empty">Invalid input. No radius or witness is rendered.</p>';$('#data-table').innerHTML='<p>No valid engine result.</p>';$('#stamp').textContent='Invalid edited input; no current result or figure.';$('#editor-error').textContent=error.message;$('#playground-outcome').textContent='No score: invalid graph';}finally{$('#draft-status').textContent=`Edited graph / unsaved / ${state.model}${state.editorInvalid?' / invalid':` / input ${result().snapshot_hash}`}`;updateExportControls();updateURL();}}
  function download(name,bytes,type){const blob=bytes instanceof Blob?bytes:new Blob([bytes],{type}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  async function exportFigure(format,column=$('#column-width').value,save=true,view=state.figure){if(state.editorInvalid)throw Error('Invalid graph: no figure can be exported.');if(!['svg','png','pdf'].includes(format)||!['single','double'].includes(column))throw Error('Unsupported figure format or width.');if(!Object.values(figureChoices).flat().some(([kind])=>kind===view))throw Error('No exportable figure in this view.');const source=svg(view,{compact:column==='single',step:Math.max(0,...inspect().map(item=>item.rank[0]))}),widthMm=column==='single'?input.tokens.figure.singleColumnMm:input.tokens.figure.doubleColumnMm;const parsed=new DOMParser().parseFromString(source,'image/svg+xml').documentElement;const viewbox=parsed.getAttribute('viewBox').trim().split(/\s+/).map(Number);if(parsed.localName!=='svg'||viewbox.length!==4||!viewbox.every(Number.isFinite)||viewbox[2]<=0||viewbox[3]<=0)throw Error('Invalid figure dimensions.');const heightMm=widthMm*viewbox[3]/viewbox[2];parsed.setAttribute('width',widthMm+'mm');parsed.setAttribute('height',heightMm+'mm');const exported=new XMLSerializer().serializeToString(parsed),name=`blast-radius-${view}-${column}-${result().snapshot_hash.slice(0,12)}`;if(format==='svg'){if(save)download(name+'.svg',exported,'image/svg+xml');return exported;}
    if(format==='pdf'){const doc=new jspdf.jsPDF({unit:'mm',format:[widthMm,heightMm],orientation:widthMm>heightMm?'landscape':'portrait',compress:true});doc.addFileToVFS('Atkinson.ttf',input.font);doc.addFont('Atkinson.ttf','Atkinson Hyperlegible','normal');doc.setFont('Atkinson Hyperlegible');await doc.svg(parsed,{x:0,y:0,width:widthMm,height:heightMm});if(save)doc.save(name+'.pdf');return doc.output('datauristring').split(',')[1];}
    const image=new Image();image.src='data:image/svg+xml;base64,'+btoa(unescape(encodeURIComponent(exported)));await image.decode();const canvas=document.createElement('canvas');canvas.width=Math.round(widthMm/25.4*input.tokens.figure.rasterDpi);canvas.height=Math.round(heightMm/25.4*input.tokens.figure.rasterDpi);const context=canvas.getContext('2d');context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(image,0,0,canvas.width,canvas.height);const data=canvas.toDataURL('image/png');if(save)download(name+'.png',Uint8Array.from(atob(data.split(',')[1]),character=>character.charCodeAt(0)),'image/png');return data.split(',')[1];}
  document.addEventListener('click',event=>{
    const target=event.target.closest('button,[data-node],[data-credential]');if(!target)return;
    if(target.dataset.view){selectView(target.dataset.view);return;}
    if(target.dataset.model){stop();if(state.view==='playground'&&state.fixture)drafts.set(state.fixture.id,$('#graph-editor').value);state.model=target.dataset.model;state.step=null;if(state.uploaded)state.uploaded=compute(state.uploaded.snapshot,state.model);if(state.preview&&state.view!=='playground')state.preview=compute(state.preview.snapshot);if(state.baseline)state.baseline=compute(state.baseline.snapshot);render();return;}
    if(target.dataset.select||target.dataset.credential){state.selected=target.dataset.select??target.dataset.credential;state.step=null;if(target.dataset.credential)state.view='disc';render();return;}
    if(target.dataset.definition){definition(target.dataset.definition);return;}
    if(target.dataset.node){nodeEvidence(target.dataset.node,target.dataset.action);return;}
    if(target.dataset.remove){removeBinding(target.dataset.remove);return;}
    if(target.dataset.edit){editGraph(target.dataset.edit);return;}
    if(target.dataset.page){state.page+=Number(target.dataset.page);sidebar();return;}
    if(target.dataset.rule){const cases=input.manifest.fixtures.filter(item=>item.requirements.includes(target.dataset.rule));showEvidence(target.dataset.rule,`<p>${cases.length?cases.map(item=>item.id+' '+item.title).join('; '):'Manual disclosure/governance requirement; not an automated fixture.'}</p><a href="../spec/METRIC_SPECIFICATION_v1.0-draft.md">Specification</a>`);return;}
    const id=target.id;
    if(target.dataset.exercise!==undefined){lesson.exercise=Number(target.dataset.exercise);lesson.mode='baseline';lesson.evaluated=false;saveLesson();render();return;}
    if(id==='lesson-reset'){lesson.exercise=0;lesson.predictions={};lesson.completed=[];lesson.mode='baseline';lesson.evaluated=false;saveLesson();render();}
    if(id==='lesson-save')download('blast-radius-lesson.json',JSON.stringify({version:1,exercise:lesson.exercise,completed:lesson.completed,predictions:lesson.predictions,synthetic:true},null,2),'application/json');
    if(id==='lesson-least-privilege'){lesson.mode='least-privilege';render();$('#lesson-result h3').textContent='Required access preserved';$('#lesson-result p').textContent='Only write was removed. Read on r0 still satisfies the stated requirement.';$('#lesson-least-privilege').disabled=true;const restored=compute(lessonGraph(),'default').credentials[0];$('#lesson-followup').textContent=`Model result: ${restored.absolute_reach}/${restored.universe_size}. Required read preserved; excess actions: 0.`;}
    if(id==='credential-toggle'){const open=target.getAttribute('aria-expanded')!=='true';target.setAttribute('aria-expanded',String(open));$('.sidebar').dataset.open=String(open);}
    if(id==='close-dialog'){$('#evidence-dialog').close();previousFocus?.focus();}
    if(id==='play')play();if(id==='step-next')scrub((state.step??0)+1);if(id==='step-back')scrub((state.step??0)-1);
    if(id==='remove-selected')removeBinding($('#binding-select').value);
    if(id==='add-binding')addBinding();
    if(id==='reset-whatif'){state.preview=null;state.baseline=null;render();}
    if(id==='evaluate')evaluate();
    if(id==='reset-playground'){drafts.delete(state.fixture.id);state.preview=null;render();}
    if(id==='redact'){state.redacted=!state.redacted;target.setAttribute('aria-pressed',String(state.redacted));target.innerHTML=icon(state.redacted?'eye-slash':'eye');render();}
    if(id==='theme'){const dark=document.documentElement.dataset.theme!=='dark';document.documentElement.dataset.theme=dark?'dark':'light';target.innerHTML=icon(dark?'sun':'moon');}
    if(id==='about')showEvidence('Visual vocabulary & licences',`<p>Disc area is proportional to canonical radius. Rings denote minimum escalation step. Color encodes the fixed sensitivity scale or named principal type. Dashed edges are declared assumptions.</p><p>All views and exports carry their source stamp. All data shown is illustrative. No real public tenant dataset or uniqueness claim is established.</p><p>Original UI: Apache-2.0. Font Awesome Free 6.7.2 SVG icons: CC-BY-4.0, Fonticons Inc. Fonts: Atkinson Hyperlegible and IBM Plex Serif, SIL OFL. D3, jsPDF, svg2pdf and js-sha256 retain their upstream licences. axe-core: MPL-2.0.</p><p><a href="../spec/VISUAL_VOCABULARY_v0.1.md">Visual Vocabulary v0.1</a></p>`);
    if(id==='copy-narrative')copyNarrative();
    if(id.startsWith('export-'))exportFigure(id.slice(7)).then(()=>announce('Figure exported')).catch(error=>showEvidence('Export error',`<p>${esc(error.message)}</p>`));
  });
  document.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&event.target.matches('[data-node],[data-credential]')&&event.target.tagName!=='BUTTON'){event.preventDefault();event.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));}});
  document.addEventListener('change',event=>{const target=event.target;if(target.id==='agent-lens'){state.nhi=target.checked;state.page=0;render();}if(target.id==='log-scale'){state.log=target.checked;render();}if(target.id==='fixture-select'){state.fixture=input.manifest.fixtures.find(item=>item.id===target.value);state.preview=null;state.selected=null;render();if(!state.fixture.valid)evaluate();}if(target.id==='incident-select'){state.incident=input.manifest.incidents.find(item=>item.id===target.value);state.control=false;state.selected=null;state.preview=null;render();}if(target.id==='incident-control'){state.control=target.checked;state.selected=null;render();}});
  document.addEventListener('input',event=>{if(event.target.id==='search'){state.query=event.target.value;state.page=0;sidebar();if(['treemap','distribution'].includes(state.view)){const position=event.target.selectionStart;render();$('#search').focus();$('#search').setSelectionRange?.(position,position);}}if(event.target.id==='step-range')scrub(Number(event.target.value));});
  document.addEventListener('submit',event=>{if(event.target.id!=='add-form')return;event.preventDefault();try{const before=baseResult(),graph=structuredClone(before.snapshot),principal=$('#add-principal').value,resource=$('#add-resource').value,action=$('#add-action').value,id='visual-binding-'+sha256(principal+resource+action).slice(0,12),provenance={connector:'visual-counterfactual',source_api:'explicit synthetic binding addition',observed_at:graph.observed_at,evidence_ref:id};graph.nodes.push({id,kind:'binding',subtype:'role_assignment',name:'Fictional added binding',effect:'allow',eligible:false,constraints:[],provenance});graph.edges.push({id:id+'-assigned',kind:'assigned',source:principal,target:id,provenance},{id:id+'-grant',kind:'grants',source:id,target:resource,actions:[action],provenance});state.baseline=before;state.preview=compute(graph);state.view='whatif';$('#evidence-dialog').close();render();}catch(error){showEvidence('Binding rejected',`<p>${esc(error.message)}</p>`);}});
  $('#file-input').addEventListener('change',async event=>{try{const file=event.target.files[0];if(!file)return;if(file.size>160*1024*1024)throw Error('Result exceeds the 160 MiB local limit.');const value=JSON.parse(await file.text());if(value.synthetic!==true||value.format_version!=='0.1'||!value.snapshot||!Array.isArray(value.credentials))throw Error('Only synthetic engine result v0.1 files are accepted.');state.uploaded=value;state.preview=null;state.fixture=null;state.incident=null;state.selected=null;state.model=value.constraint_model;state.view='treemap';render();}catch(error){showEvidence('Result rejected',`<p>${esc(error.message)}</p>`);}});
  document.addEventListener('submit',event=>{if(event.target.id==='lesson-form'){event.preventDefault();const prediction=new FormData(event.target).get('prediction');if(!['0','1','2'].includes(prediction))return;lesson.predictions[lesson.exercise]=prediction;lesson.mode='baseline';lesson.evaluated=true;if(!lesson.completed.includes(lesson.exercise))lesson.completed.push(lesson.exercise);saveLesson();render();$('#lesson-result').scrollIntoView({block:'nearest'});}});
  const url=new URLSearchParams(location.hash.slice(1));if(titles[url.get('view')])state.view=url.get('view');if(models.includes(url.get('model')))state.model=url.get('model');state.nhi=url.get('lens')==='nhi';$('#agent-lens').checked=state.nhi;
  if(state.view==='playground')state.fixture=input.manifest.fixtures[0];
  if(state.view==='incidents')state.incident=input.manifest.incidents[0];
  state.selected=baseResult().credentials[Math.max(0,Number(url.get('item')??0))]?.credential_id;
  $('#figure-kind').addEventListener('change',event=>{state.figure=event.target.value;});
  document.addEventListener('input',event=>{if(event.target.id==='graph-editor'&&state.fixture){drafts.set(state.fixture.id,event.target.value);state.editorInvalid=true;$('#metric-strip').innerHTML='';$('#playground-outcome').textContent='Edited input / not evaluated';$('#draft-status').textContent=`Edited graph / unsaved / ${state.model}`;updateExportControls();}});
  globalThis.BRApp={state,result,render,selectView,svg,exportFigure,compute,inspect,filtered,narrative,copyNarrative,metricRows,removeBinding,stop,summary,lesson};
  render();
})();